# General settings
seed: 20
dry_run: False  # used for testing purposes; if True, then only one iteration is performed

# Data settings:
data:
  slices_range: 100
  slices_per_view: 3  # cannot be changed; depends on the architecture input
  features_out: '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/output/features/nifd_adni_aibl'
  diagnoses_info:
    valid_diagnoses:
      - CON
      - BV
      - SV
      - PNFA
      - AD
      - MCI
      - CN
      - LMCI
      - EMCI
      - SMC
      - AD Dementia
      - Cognitively normal
      - PASS # a dummy label (for data that is not used for linear evaluation, e.g. the PPMI dataset)
    control_labels:
      - CON
      - CN
      - Cognitively normal
    ftd_labels:
      - BV
      - SV
      - PNFA
    merge_ftd: True  # will be encoded as 'FTD'
    ad_labels:  # will be encoded as 'AD'
      - AD Dementia
      - AD


# NNCLR settings:
nnclr:
  checkpoint: '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/output/checkpoints/nnclr.ckpt'
  epochs: 1000
  save_nepoch: 100  # a model will be saved every nth epoch
  batch_size: 74
  data:
    # A list of the paths to the CAPS directories:
    - caps_directories:
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/nifd/CAPS/'
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/adni/data/adni3/CAPS/'
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/aibl/CAPS/'

    # A list of the paths to the TSV files containing targets/labels:
    - info_data_files:
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/nifd/info_data.tsv'
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/adni/info_data.tsv'
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/aibl/info_data.tsv'


# Setting for the linear evaluation of the NNCLR model:
linear_eval:
  checkpoint: '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/output/checkpoints/nnclr_le_binary.ckpt'
  epochs: 200
  batch_size: 32
  replicas: 100  # for each sample # replicas random slices are provided to predict a diagnosis
  replicas_extraction: 1  # extract # replicas_extraction random slices from each sample
  data:
    # A list of the paths to the CAPS directories:
    - caps_directories:
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/nifd/CAPS/'
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/adni/data/adni3/CAPS/'
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/aibl/CAPS/'

    # A list of the paths to the TSV files containing targets/labels:
    - info_data_files:
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/nifd/info_data.tsv'
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/adni/info_data.tsv'
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/aibl/info_data.tsv'
  eval_labels:
    - CN
    - AD

# Setting for the linear evaluation of the NNCLR model on the independent datasets:
independent_linear_eval:
  checkpoint: '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/output/checkpoints/nnclr_le_binary.ckpt'
  epochs: 200
  batch_size: 32
  replicas: 100  # for each sample # replicas random slices are provided to predict a diagnosis
  replicas_extraction: 1  # extract # replicas_extraction random slices from each sample
  data:
    # A list of the paths to the CAPS directories:
    - caps_directories:
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/oasis/CAPS/'
    # A list of the paths to the TSV files containing targets/labels:
    - info_data_files:
      - '/data_dzne_archiv/Studien/ClinicNET/clinic-net-git/data/oasis/info_data.tsv'
  eval_labels:
    - CN
    - AD


# LRP settings:
lrp:
  is_train_set: False  # if False, then a train set will be used
  checkpoint: ''
  batch_size: 256
  classes: 2
